variables:
  WORK_PATH: /home/esp/esp-open-rtos/examples/project
  FIRMWARE_BIN_DIR: firmware
  WIFI_VARS_PATH: include/private_ssid_config.h
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - api-docs
  - docs

# template jobs
.code-style:
  stage: lint
  image: marcotti/esp-open-rtos
  before_script:
    - cd $WORK_PATH
    - cp -r $CI_PROJECT_DIR/$DEVICE_ESP_DIR/* .
    - envsubst < $WIFI_VARS_PATH | sponge $WIFI_VARS_PATH
  script:
    - make lint
  tags:
    - local
    - amd64

.build-device:
  stage: build
  image: marcotti/esp-open-rtos
  before_script:
    - cd $WORK_PATH
    - cp -r $CI_PROJECT_DIR/$DEVICE_ESP_DIR/* .
    - envsubst < $WIFI_VARS_PATH | sponge $WIFI_VARS_PATH
  script:
    - make
    - mkdir $CI_PROJECT_DIR/$DEVICE_ESP_DIR/firmware
    - cp $FIRMWARE_BIN_DIR/* $CI_PROJECT_DIR/$DEVICE_ESP_DIR/$FIRMWARE_BIN_DIR/image.bin
  tags:
    - local
    - amd64
  artifacts:
    paths:
    - $CI_PROJECT_DIR/$DEVICE_ESP_DIR/$FIRMWARE_BIN_DIR/image.bin
    expire_in: 1 week

.test-device:
  image: marcotti/esptool-minimal:latest
  variables:
    ESP_PORT: /dev/ttyUSB0
    BAUD_RATE: 115200
    FW_POSITION: 0x2000
  stage: test
  before_script:
    - esptool.py --port $ESP_PORT --baud $BAUD_RATE write_flash $FW_POSITION $DEVICE_ESP_DIR/$FIRMWARE_BIN_DIR/*.bin
    - pip install websockets
  script:
    - python3 -m unittest discover -v -s $DEVICE/tests
  tags:
    - rpi

.aero:
  variables:
    DEVICE: aeropendulum
    DEVICE_ESP_DIR: aeropendulum/esp

.experimental:
  variables:
    DEVICE: experimental
    DEVICE_ESP_DIR: experimental/esp

# device specific jobs
style-aero:
  extends:
    - .aero
    - .code-style
  needs: []

style-experimental:
  extends:
    - .experimental
    - .code-style
  needs: []

build-aero:
  extends:
    - .aero
    - .build-device
  needs: []

build-experimental:
  extends:
    - .experimental
    - .build-device
  needs: []

test-experimental:
  extends:
    - .experimental
    - .test-device
  needs: ["build-experimental"]

test-aero:
  extends:
    - .aero
    - .test-device
  needs: ["build-aero"]

# generic jobs
openapi:
  stage: api-docs
  image: node:latest
  script:
  - npm install -g redoc-cli
  - mkdir -p public/
  - redoc-cli bundle -o public/openapi.html docs/api.yaml
  artifacts:
    paths:
    - public
  only:
    - master

pages:
  stage: docs
  image: nxpleuvenjenkins/doxygen
  script:
    - doxygen .gci/Doxyfile
    - mv $CI_PROJECT_DIR/public/html/* $CI_PROJECT_DIR/public
  tags:
    - local
    - amd64
  artifacts:
    paths:
      - $CI_PROJECT_DIR/public/*
    expire_in: 1 week
  only:
    - master
