variables:
  CI_ESP_AEROPENDULUM_DIR: aeropendulum/esp
  CI_AEROPENDULUM_DIR: aeropendulum
  WORK_PATH: /home/esp/esp-open-rtos/examples/project
  FIRMWARE_BIN_DIR: firmware
  WIFI_VARS_PATH: include/private_ssid_config.h
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - burn
  - test

build-aero:
  stage: build
  before_script:
    - cd $WORK_PATH
    - cp -r $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/* .
    - envsubst < $WIFI_VARS_PATH | sponge $WIFI_VARS_PATH
  script:
    - make
    - cp $FIRMWARE_BIN_DIR/* $CI_PROJECT_DIR/image.bin
  tags:
    - brasov-fw-burn
  artifacts:
    paths:
    - $CI_PROJECT_DIR/image.bin
    expire_in: 1 week

flash-aero:
  stage: burn
  before_script:
    - cd $WORK_PATH
    - cp -r $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/* .
  script:
    - make flash_after_build
  tags:
    - brasov-fw-burn
  dependencies:
    - build-aero

test-aero:
  stage: test
  script:
    - python3 -m unittest discover -v -s $CI_AEROPENDULUM_DIR/tests
  tags:
    - brasov-testing
