variables:
  CI_ESP_AEROPENDULUM_DIR: aeropendulum/esp
  CI_AEROPENDULUM_DIR: aeropendulum
  WORK_PATH: /home/esp/esp-open-rtos/examples/project
  FIRMWARE_BIN_DIR: firmware
  WIFI_VARS_PATH: include/private_ssid_config.h
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - burn
  - test
  - docs

code-style:
  stage: lint
  before_script:
    - cd $WORK_PATH
    - cp -r $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/* .
    - envsubst < $WIFI_VARS_PATH | sponge $WIFI_VARS_PATH
  script:
    - make lint
  tags:
    - fw-build

build-aero:
  stage: build
  before_script:
    - cd $WORK_PATH
    - cp -r $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/* .
    - envsubst < $WIFI_VARS_PATH | sponge $WIFI_VARS_PATH
  script:
    - make
    - mkdir $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/firmware
    - cp $FIRMWARE_BIN_DIR/* $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/$FIRMWARE_BIN_DIR/image.bin
  tags:
    - fw-build
  artifacts:
    paths:
    - $CI_PROJECT_DIR/$CI_ESP_AEROPENDULUM_DIR/$FIRMWARE_BIN_DIR/image.bin
    expire_in: 1 week

flash-aero:
  variables:
    ESP_PORT: /dev/ttyUSB0
    BAUD_RATE: 115200
    FW_POSITION: 0x2000
  stage: burn
  script:
    - esptool.py --port $ESP_PORT --baud $BAUD_RATE write_flash $FW_POSITION $CI_ESP_AEROPENDULUM_DIR/$FIRMWARE_BIN_DIR/*.bin
  tags:
    - fw-burn
  dependencies:
    - build-aero

test-aero:
  stage: test
  script:
    - python3 -m unittest discover -v -s $CI_AEROPENDULUM_DIR/tests
  tags:
    - testing

pages:
  stage: docs
  image: nxpleuvenjenkins/doxygen
  script:
    - doxygen .gci/Doxyfile
    - mv $CI_PROJECT_DIR/public/html/* $CI_PROJECT_DIR/public
  tags:
    - testing
  artifacts:
    paths:
      - $CI_PROJECT_DIR/public/*
    expire_in: 1 week
